const {app,BrowserWindow,ipcMain}=require('electron');
const path=require('path'),fs=require('fs'),crypto=require('crypto');
let win,dbRoot='C:\\xampp\\htdocs\\OFST',session=null,booking=null,tracking=null,lastTelemetry=0;
const XP='http://127.0.0.1:8086',M2FT=3.280839895,MPS2KT=1.943844492;
let xpApi='v1',refs={},polling=false;
const DR={lat:'sim/flightmodel/position/latitude',lon:'sim/flightmodel/position/longitude',elev:'sim/flightmodel/position/elevation',agl:'sim/flightmodel/position/y_agl',ias:'sim/flightmodel/position/indicated_airspeed',tas:'sim/flightmodel/position/true_airspeed',gs:'sim/flightmodel/position/groundspeed',vs:'sim/flightmodel/position/vh_ind_fpm',hdg:'sim/flightmodel/position/psi',pitch:'sim/flightmodel/position/theta',roll:'sim/flightmodel/position/phi',fuel:'sim/flightmodel/weight/m_fuel_total',weight:'sim/flightmodel/weight/m_total',flaps:'sim/cockpit2/controls/flap_handle_deploy_ratio',gear:'sim/flightmodel2/gear/deploy_ratio',park:'sim/cockpit2/controls/parking_brake_ratio',eng:'sim/flightmodel/engine/ENGN_running',n1:'sim/flightmodel/engine/ENGN_N1_',n2:'sim/flightmodel/engine/ENGN_N2_',throttle:'sim/cockpit2/engine/actuators/throttle_ratio_all',beacon:'sim/cockpit2/switches/beacon_on',nav:'sim/cockpit2/switches/navigation_lights_on',strobe:'sim/cockpit2/switches/strobe_lights_on',landing:'sim/cockpit2/switches/landing_lights_on',taxi:'sim/cockpit2/switches/taxi_light_on',seatbelt:'sim/cockpit2/switches/fasten_seat_belts',spoilers:'sim/cockpit2/controls/speedbrake_ratio',reversers:'sim/cockpit2/annunciators/reverser_deployed'};
function parseCSV(s){let rows=[],r=[],c='',q=false;for(let i=0;i<s.length;i++){let x=s[i];if(q){if(x==='"'&&s[i+1]==='"'){c+='"';i++}else if(x==='"')q=false;else c+=x}else if(x==='"')q=true;else if(x===','){r.push(c);c=''}else if(x==='\n'){r.push(c.replace(/\r$/,''));rows.push(r);r=[];c=''}else c+=x}if(c||r.length){r.push(c);rows.push(r)}if(!rows.length)return[];let h=rows.shift().map(x=>x.replace(/^\uFEFF/,'').trim());return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()])))}
function read(name){let f=path.join(dbRoot,name);return fs.existsSync(f)?parseCSV(fs.readFileSync(f,'utf8')):[]}
function esc(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function append(name,cols,o){let f=path.join(dbRoot,name),exists=fs.existsSync(f)&&fs.statSync(f).size;fs.mkdirSync(dbRoot,{recursive:true});fs.appendFileSync(f,(exists?'':cols.join(',')+'\r\n')+cols.map(k=>esc(o[k])).join(',')+'\r\n')}
function sha(v){return crypto.createHash('sha256').update(v).digest('hex')}
function activeBooking(id){return read('OFST_bookings.csv').filter(x=>x.pilot_id===id&&String(x.status).toUpperCase()==='BOOKED').at(-1)||null}
function refreshBooking(){if(!session||tracking)return booking;let next=activeBooking(session.pilot_id),old=booking?.booking_id||'',now=next?.booking_id||'';booking=next;if(old!==now)win?.webContents.send('booking-updated',booking);return booking}
function phase(t){let gs=+t.gs_kt||0,agl=+t.agl_ft||0,vs=+t.vs_fpm||0,on=!!t.on_ground,eng=+t.engines_running||0;if(on&&!eng&&gs<1)return 'COLD & DARK';if(on&&eng&&gs<3)return 'ENGINES STARTED';if(on&&gs>=3&&gs<45)return tracking?.airborne?'TAXI IN':'TAXI OUT';if(on&&gs>=45)return tracking?.airborne?'LANDING ROLL':'TAKEOFF ROLL';if(!on){if(tracking)tracking.airborne=true;if(agl<1500&&vs>100)return 'INITIAL CLIMB';if(vs>300)return 'CLIMB';if(vs<-300&&agl>3000)return 'DESCENT';if(agl<3000&&vs<=0)return 'APPROACH';return 'CRUISE'}return 'PARKED'}
function record(t){if(!tracking)return;let p=phase(t),now=new Date().toISOString();if(p!==tracking.phase){event(p,t);tracking.phase=p}let cols=['utc','pilot_id','booking_id','callsign','registration','origin','destination','phase','lat','lon','alt_ft','agl_ft','ias_kt','tas_kt','gs_kt','vs_fpm','heading_deg','pitch_deg','roll_deg','fuel_kg','weight_kg','flaps','gear','parking_brake','engines_running','n1','n2','throttle','beacon','nav_lights','strobe','landing_lights','taxi_light','seatbelt','spoilers','reversers','nearest_airport'];append('OFST_flight_telemetry.csv',cols,{utc:now,pilot_id:session.pilot_id,booking_id:booking.booking_id,callsign:booking.callsign||booking.flight_number,registration:booking.registration,origin:booking.origin_icao,destination:booking.destination_icao,phase:p,...t});if(p==='PARKED'&&tracking.airborne&&String(t.nearest_airport||'').toUpperCase()===String(booking.destination_icao||'').toUpperCase()){event('FLIGHT COMPLETE',t);tracking=null;win.webContents.send('flight-complete',t)}}
function event(type,t={}){append('OFST_tracker_events.csv',['utc','pilot_id','booking_id','event','payload'],{utc:new Date().toISOString(),pilot_id:session?.pilot_id,booking_id:booking?.booking_id,event:type,payload:JSON.stringify(t)})}
function create(){win=new BrowserWindow({width:1500,height:940,minWidth:1180,minHeight:760,backgroundColor:'#05090c',show:false,title:'OmanFS Flight Tracker',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.setMenuBarVisibility(false);win.loadFile(path.join(__dirname,'index.html'));win.once('ready-to-show',()=>win.show())}
async function jget(url,timeout=1800){let c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{let r=await fetch(url,{headers:{Accept:'application/json'},signal:c.signal});if(!r.ok)throw Error(String(r.status));return await r.json()}finally{clearTimeout(tm)}}
async function detectApi(){try{let c=await jget(XP+'/api/capabilities');let vs=c?.api?.versions||[];xpApi=vs.includes('v3')?'v3':vs.includes('v2')?'v2':'v1';return true}catch{try{await jget(XP+'/api/v1/datarefs/count');xpApi='v1';return true}catch{return false}}}
async function resolveRefs(){refs={};for(let [k,name] of Object.entries(DR)){try{let u=XP+'/api/'+xpApi+'/datarefs?filter%5Bname%5D='+encodeURIComponent(name)+'&limit=2';let x=await jget(u);if(x?.data?.[0])refs[k]=x.data[0]}catch{}}return Object.keys(refs).length>=10}
async function rv(k){let r=refs[k];if(!r)return null;try{return (await jget(XP+'/api/'+xpApi+'/datarefs/'+r.id+'/value',900)).data}catch{return null}}
function arr(v){return Array.isArray(v)?v:[v]}
function avg(v){let a=arr(v).map(Number).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function any(v){return arr(v).some(x=>+x>0.5)}
async function sample(){if(polling)return;polling=true;try{let keys=Object.keys(refs),vals=await Promise.all(keys.map(rv)),v=Object.fromEntries(keys.map((k,i)=>[k,vals[i]]));let agl=(+v.agl||0)*M2FT,onGround=agl<5&&(+v.gs||0)<90;let airborne=tracking?.airborne||!onGround;let nearest=booking?(airborne?(onGround?booking.destination_icao:'ENROUTE'):booking.origin_icao):'';let t={lat:+v.lat||0,lon:+v.lon||0,alt_ft:(+v.elev||0)*M2FT,agl_ft:agl,ias_kt:+v.ias||0,tas_kt:(+v.tas||0)*MPS2KT,gs_kt:(+v.gs||0)*MPS2KT,vs_fpm:+v.vs||0,heading_deg:+v.hdg||0,pitch_deg:+v.pitch||0,roll_deg:+v.roll||0,fuel_kg:+v.fuel||0,weight_kg:+v.weight||0,flaps:+v.flaps||0,gear:any(v.gear),parking_brake:(+v.park||0)>.5,engines_running:any(v.eng),n1:avg(v.n1),n2:avg(v.n2),throttle:+v.throttle||0,beacon:!!+v.beacon,nav_lights:!!+v.nav,strobe:!!+v.strobe,landing_lights:any(v.landing),taxi_light:any(v.taxi),seatbelt:!!+v.seatbelt,spoilers:+v.spoilers||0,reversers:any(v.reversers),on_ground:onGround,nearest_airport:nearest,registration:booking?.registration||''};t.phase=phase(t);lastTelemetry=Date.now();win?.webContents.send('telemetry',t);record(t)}finally{polling=false}}
async function xplane(){let ready=false;setInterval(async()=>{if(!ready){ready=await detectApi();if(ready)ready=await resolveRefs()}if(ready){try{await sample()}catch{ready=false;refs={}}}win?.webContents.send('sim-status',ready&&Date.now()-lastTelemetry<3000)},500)}
ipcMain.handle('login',(_,email,password)=>{let p=read('OFST_pilots.csv').find(x=>x.email?.toLowerCase()===String(email).trim().toLowerCase()&&x.password_sha256===sha(String(password)));if(!p)return {ok:false,error:'Email or password is incorrect.'};session=p;booking=activeBooking(p.pilot_id);return {ok:true,pilot:p,booking}});
ipcMain.handle('refresh-booking',()=>({ok:!!session,booking:refreshBooking()}));
ipcMain.handle('start-track',(_,airport)=>{refreshBooking();if(!session||!booking)return {ok:false,error:'No active booking.'};if(String(airport||'').toUpperCase()!==String(booking.origin_icao||'').toUpperCase())return {ok:false,error:`Aircraft is at ${airport||'an unknown airport'}, but this flight starts at ${booking.origin_icao}.`};tracking={started:new Date().toISOString(),phase:'',airborne:false};event('TRACKING STARTED');return {ok:true}});
ipcMain.handle('db-status',()=>({root:dbRoot,ok:fs.existsSync(path.join(dbRoot,'OFST_pilots.csv'))}));
app.whenReady().then(()=>{create();xplane();setInterval(refreshBooking,3000)});app.on('window-all-closed',()=>app.quit());