const {app,BrowserWindow,ipcMain}=require('electron');
const path=require('path'),fs=require('fs'),crypto=require('crypto'),dgram=require('dgram');
let win,dbRoot='C:\\xampp\\htdocs\\OFST',session=null,booking=null,tracking=null,lastTelemetry=0;
function parseCSV(s){let rows=[],r=[],c='',q=false;for(let i=0;i<s.length;i++){let x=s[i];if(q){if(x==='"'&&s[i+1]==='"'){c+='"';i++}else if(x==='"')q=false;else c+=x}else if(x==='"')q=true;else if(x===','){r.push(c);c=''}else if(x==='\n'){r.push(c.replace(/\r$/,''));rows.push(r);r=[];c=''}else c+=x}if(c||r.length){r.push(c);rows.push(r)}if(!rows.length)return[];let h=rows.shift().map(x=>x.replace(/^\uFEFF/,'').trim());return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()])))}
function read(name){let f=path.join(dbRoot,name);return fs.existsSync(f)?parseCSV(fs.readFileSync(f,'utf8')):[]}
function esc(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function append(name,cols,o){let f=path.join(dbRoot,name),exists=fs.existsSync(f)&&fs.statSync(f).size;fs.mkdirSync(dbRoot,{recursive:true});fs.appendFileSync(f,(exists?'':cols.join(',')+'\r\n')+cols.map(k=>esc(o[k])).join(',')+'\r\n')}
function sha(v){return crypto.createHash('sha256').update(v).digest('hex')}
function activeBooking(id){return read('OFST_bookings.csv').filter(x=>x.pilot_id===id&&String(x.status).toUpperCase()==='BOOKED').at(-1)||null}
function phase(t){let gs=+t.gs_kt||0,agl=+t.agl_ft||0,vs=+t.vs_fpm||0,on=!!t.on_ground,eng=+t.engines_running||0;if(on&&!eng&&gs<1)return 'COLD & DARK';if(on&&eng&&gs<3)return 'ENGINES STARTED';if(on&&gs>=3&&gs<45)return tracking?.airborne?'TAXI IN':'TAXI OUT';if(on&&gs>=45)return tracking?.airborne?'LANDING ROLL':'TAKEOFF ROLL';if(!on){tracking.airborne=true;if(agl<1500&&vs>100)return 'INITIAL CLIMB';if(vs>300)return 'CLIMB';if(vs<-300&&agl>3000)return 'DESCENT';if(agl<3000&&vs<=0)return 'APPROACH';return 'CRUISE'}return 'PARKED'}
function record(t){if(!tracking)return;let p=phase(t),now=new Date().toISOString();if(p!==tracking.phase){event(p,t);tracking.phase=p}let cols=['utc','pilot_id','booking_id','callsign','registration','origin','destination','phase','lat','lon','alt_ft','agl_ft','ias_kt','tas_kt','gs_kt','vs_fpm','heading_deg','pitch_deg','roll_deg','fuel_kg','weight_kg','flaps','gear','parking_brake','engines_running','n1','n2','throttle','beacon','nav_lights','strobe','landing_lights','taxi_light','seatbelt','spoilers','reversers','nearest_airport'];append('OFST_flight_telemetry.csv',cols,{utc:now,pilot_id:session.pilot_id,booking_id:booking.booking_id,callsign:booking.callsign||booking.flight_number,registration:booking.registration,origin:booking.origin_icao,destination:booking.destination_icao,phase:p,...t});if(p==='PARKED'&&tracking.airborne&&String(t.nearest_airport||'').toUpperCase()===String(booking.destination_icao||'').toUpperCase()){event('FLIGHT COMPLETE',t);tracking=null;win.webContents.send('flight-complete',t)}}
function event(type,t={}){append('OFST_tracker_events.csv',['utc','pilot_id','booking_id','event','payload'],{utc:new Date().toISOString(),pilot_id:session?.pilot_id,booking_id:booking?.booking_id,event:type,payload:JSON.stringify(t)})}
function create(){win=new BrowserWindow({width:1500,height:940,minWidth:1180,minHeight:760,backgroundColor:'#05090c',show:false,title:'OmanFS Flight Tracker',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.setMenuBarVisibility(false);win.loadFile(path.join(__dirname,'index.html'));win.once('ready-to-show',()=>win.show())}
function udp(){let s=dgram.createSocket('udp4');s.on('message',b=>{try{let t=JSON.parse(b);lastTelemetry=Date.now();if(win)win.webContents.send('telemetry',t);record(t)}catch{}});s.bind(49091,'127.0.0.1');setInterval(()=>win?.webContents.send('sim-status',Date.now()-lastTelemetry<2500),1000)}
ipcMain.handle('login',(_,email,password)=>{let p=read('OFST_pilots.csv').find(x=>x.email?.toLowerCase()===String(email).trim().toLowerCase()&&x.password_sha256===sha(String(password)));if(!p)return {ok:false,error:'Email or password is incorrect.'};session=p;booking=activeBooking(p.pilot_id);return {ok:true,pilot:p,booking}});
ipcMain.handle('start-track',(_,airport)=>{if(!session||!booking)return {ok:false,error:'No active booking.'};if(String(airport||'').toUpperCase()!==String(booking.origin_icao||'').toUpperCase())return {ok:false,error:`Aircraft is at ${airport||'an unknown airport'}, but this flight starts at ${booking.origin_icao}.`};tracking={started:new Date().toISOString(),phase:'',airborne:false};event('TRACKING STARTED');return {ok:true}});
ipcMain.handle('db-status',()=>({root:dbRoot,ok:fs.existsSync(path.join(dbRoot,'OFST_pilots.csv'))}));
app.whenReady().then(()=>{create();udp()});app.on('window-all-closed',()=>app.quit());